<a href="https://colab.research.google.com/github/Humaidabdullah/Deep-Learning-PadhAI/blob/master/Sigmoid%20Neuron/SigmoidNeuronClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Sigmoid Neuron Class

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
class SigmoidNeuron:

  def __init__(self):
    self.w = None
    self.b = None

  def perceptron(self, x):
    return np.dot(x,self.w.T) + self.b
  
  def sigmoid(self, x):
    return 1.0/(1.0 + np.exp(-x))

  def grad_w(self, x, y):
    y_pred = self.sigmoid(self.perceptron(x))
    return (y_pred - y) * y_pred * (1-y_pred) * x

  def grad_b(self, x, y):
    y_pred = self.sigmoid(self.perceptron(x))
    return (y_pred - y) * y_pred * (1-y_pred) 
  
  def fit(self, X, Y, epochs=1, lr = 1, initialize = True):
    if initialize:
      self.w = np.random.rand(1,X.shape[1]) #(row,col)
      self.b = 0
    for i in range(epochs):
      dw = 0
      db = 0
      for x,y in zip(X,Y):
        dw += self.grad_w(x,y)
        db += self.grad_b(x,y)
      self.w -= lr * dw
      self.b -= lr * db

# Fit for toy data

In [0]:
X = np.asarray([[2.5,2.5],[4,-1],[1,-4],[3,1.34],[2,4],[1,5]])
Y = [1,1,1,0,0,0]

In [0]:
sn = SigmoidNeuron()
sn.fit(X,Y,1,0.25)

In [15]:
for i in range(10):
  print(sn.w,sn.b)
  sn.fit(X,Y,1,0.5,False)

[[ 0.05472587 -0.73476627]] [-0.04717182]
[[ 0.21296263 -0.6826255 ]] [0.00485272]
[[ 0.27037902 -0.61769902]] [0.03023957]
[[ 0.28939603 -0.5716472 ]] [0.04320366]
[[ 0.28884956 -0.54878518]] [0.04854791]
[[ 0.28281764 -0.53884159]] [0.05123347]
[[ 0.2774491  -0.53382359]] [0.05374403]
[[ 0.27356912 -0.53098484]] [0.05653716]
[[ 0.27078094 -0.52937121]] [0.05955917]
[[ 0.26868398 -0.52849704]] [0.0627208]
